# Generated by Django 4.1.7 on 2023-07-16 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_wbs', '0001_initial'),
        ('z_tab_pmb_quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERFQuantum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erf_quantum_code', models.CharField(max_length=55, unique=True, verbose_name='ERF Quantum Code')),
                ('erf_quantum_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='ERF Quantum Title')),
                ('comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
                ('erf_ca_code', models.CharField(max_length=55, unique=True, verbose_name='ERF Cost Account Code')),
                ('erf_ca_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='ERF Cost Account Title')),
                ('erf_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='ERF Hours')),
                ('erf_costs', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True, verbose_name='ERF Costs')),
                ('cost_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_wbs.costtype', verbose_name='Cost Type ID')),
                ('pmb_L03_wp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='z_tab_pmb_quantum.pmbl03wp', verbose_name='PMB L03 WP ID')),
            ],
            options={
                'verbose_name_plural': 'Estimate Reference File - Quantum',
                'db_table': 'erf_quantum',
                'ordering': ['erf_quantum_code'],
                'managed': True,
                'unique_together': {('pmb_L03_wp', 'erf_ca_code', 'erf_quantum_code')},
            },
        ),
        migrations.DeleteModel(
            name='ERF',
        ),
    ]
